/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ApplicationLogo: typeof import('./../components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./../layouts/AuthenticatedLayout.vue')['default']
    Checkbox: typeof import('./../components/Checkbox.vue')['default']
    DangerButton: typeof import('./../components/DangerButton.vue')['default']
    Dropdown: typeof import('./../components/Dropdown.vue')['default']
    DropdownLink: typeof import('./../components/DropdownLink.vue')['default']
    GuestLayout: typeof import('./../layouts/GuestLayout.vue')['default']
    InputError: typeof import('./../components/InputError.vue')['default']
    InputLabel: typeof import('./../components/InputLabel.vue')['default']
    Modal: typeof import('./../components/Modal.vue')['default']
    NavLink: typeof import('./../components/NavLink.vue')['default']
    PrimaryButton: typeof import('./../components/PrimaryButton.vue')['default']
    ResponsiveNavLink: typeof import('./../components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./../components/SecondaryButton.vue')['default']
    TextInput: typeof import('./../components/TextInput.vue')['default']
  }
}
